ALTER TABLE users
  ADD COLUMN IF NOT EXISTS base_daily_cap_usd INT NOT NULL DEFAULT 5000,
  ADD COLUMN IF NOT EXISTS friend_bonus_usd_today INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS friend_bonus_date DATE NOT NULL DEFAULT (CURRENT_DATE);
